[workspace]
members = ["sudoku"]
resolver = "2"

[workspace.dependencies]
cosmwasm-std = { version = "2.1.5", features = ["staking"] }
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
thiserror = "2.0.6"
cosmwasm-schema = "2.1.5"

cw-multi-test = "2.2.0"
serde_json = "1.0.135"